import Head from 'next/head'
import GroupList from '../components/Group/List';
import CarouselList from '../components/Slider/List';
import movies from '@/mocks/movies.json'

import "swiper/swiper.min.css";

export default function Home(props) {

  const {movies} = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CarouselList movies={movies.results.slice(0, 8)} />
      <GroupList title="IN THEATER" movies={movies.results.slice(0, 8)} />
      <GroupList title="ON TV" movies={movies.results.slice(8, 16)} />
    </>
  )
}


export const getServerSideProps = async ()=>{
  return {
    props:{
      movies
    }
  }
}
